### ISSUE TITLE
Request: a command to fully repair items

### ISSUE THREAD

**Issue by PrincessRTFM** [JereKuusela/valheim-dev#16]
Ideally, it would be nice to be able to repair the held item, worn equipment, or the entire inventory (preferably also repairing anything worn at the same time, to account for mods that add new equipment slots) by passing arguments, such as `repair [hand|worn|all]`, optionally allowing more than one specifier (such that `repair hand worn` works to repair any equipped item and also any worn gear).

Minimally, I'd love to be able to use a command to just repair everything I'm wearing and in my inventory.

**Comment by JereKuusela** [comment]
I was thinking of doing

`inventory repair hand/worn/all` with all being the default option.

Does that sound ok?

**Comment by PrincessRTFM** [comment]
Sounds great!

**Comment by PrincessRTFM** [comment]
Looks like this is in, so I'll close this request
