### ISSUE TITLE
Request: a command to manipulate item levels in the inventory

### ISSUE THREAD

**Issue by PrincessRTFM** [JereKuusela/valheim-dev#17]
Similar to the requested `repair` command, an `upgrade` command to adjust the level of a held or worn item (or all items at once) would be nice. Possible considerations:

- a target level (would need to be checked for validity)
- a target specifier (`held`/`worn`/`all`, maybe with a default value?)
- a flag to allow _downgrading_ of items that are above the target level (defaulting to false)

Possible usage: `upgrade <level> [<filter>] [<downgrade?>]`

Usage example: `upgrade 4` or `upgrade 4 worn true` or `upgrade 3 held`

**Comment by JereKuusela** [comment]
I was thinking of doing

`inventory upgrade hand/worn/all [amount or max level if not given]`
and
`inventory level hand/worn/all [amount]`

So that you could do `inventory upgrade hand 2` to increase by two levels or  `inventory upgrade hand 2` to set it to the level 2.

Does that sound ok?

**Comment by PrincessRTFM** [comment]
That sounds great!

**Comment by PrincessRTFM** [comment]
Looks like this is in, so I'll close this request
