### ISSUE TITLE
1.3.5 release not working

### ISSUE THREAD

**Issue by jasonraypayne** [JereKuusela/valheim-dev#18]
Puts $ signs in front of menu options and makes connecting in a server list impossible.  Running stable public Valheim, not PTB.

**Comment by JereKuusela** [comment]
This is fixed in the 1.3.6 version. Sorry for the issue.

**Comment by jasonraypayne** [comment]
Cool!  Thanks and great mod. Jason Payne | ***@***.*** Nov 23, 2022, at 2:13 AM, Jere Kuusela ***@***.***> wrote:﻿
This is fixed in the 1.3.6 version. Sorry for the issue.
