### ISSUE TITLE
[REQUEST] Allow sleeping while ghosted players are online and out of bed

### ISSUE THREAD

**Issue by PrincessRTFM** [JereKuusela/valheim-dev#21]
I have a server that my friends play on, but I don't. I'm the admin for the server though, and sometimes I like to just log in and look around, to see what they've built and everything. Unfortunately, if I'm online, they can't sleep unless I get into bed too. It would be nice if being in ghost mode (or having some other kind of flag, maybe?) would allow the game to ignore me when deciding if everyone's asleep, so that I don't disrupt their game.

**Comment by JereKuusela** [comment]
This might now work on the latest version but didn't test at all.
