### ISSUE TITLE
Allow using player names in `goto` to teleport to another person

### ISSUE THREAD

**Issue by PrincessRTFM** [JereKuusela/valheim-dev#25]
Currently, to teleport to someone else, you need to use `pos <name>`, followed by typing the returned coordinates in a subsequent `goto <x>,<z>[,<y>]` command. It would be much more convenient to be able to simply type `goto <player>` (or, since there's already `goto last`, possibly `goto player <player>` to avoid potential conflicts?) in order to effectively combine those commands, going directly to someone's current position.

**Comment by JereKuusela** [comment]
Good idea, I will try to remember.
