### ISSUE TITLE
Xbox players seem to bypass blacklist

### ISSUE THREAD

**Issue by Raakalainen** [JereKuusela/valheim-dev#29]
Apparently, xbox players are able to use any devcommands if they can get their console working.

If the devs won't tackle it quick enough, maybe Jere will just mod it right 🗡️

**Comment by Raakalainen** [comment]
It seems there is a trainer called wemod and some others but I couldn't get their names sadly, one of em enables m_cheat in the _console object and lets them use devcommands on any server.

Seems like there's not much that can be done about it afaik, as it's a clientside thing. 
sorry if this wasted your time :)

**Comment by JereKuusela** [comment]
Yeah, unfortunately my mod is pretty much the only one that has some kind of admin checks.
