### ISSUE TITLE
Devcommands: Unauthorized Access/Context after last server update

### ISSUE THREAD

**Issue by kkuez** [JereKuusela/valheim-dev#31]
After the last servers update, devcommands wont work any longer.
Message is "Unauthorized to use dev commands", even though players are in adminlist.

**Comment by JereKuusela** [comment]
There has been no change to the admin feature for a while. Did you just enable crossplay while having SteamIds on the adminlist?

**Comment by kkuez** [comment]
> There has been no change to the admin feature for a while. Did you just enable crossplay while having SteamIds on the adminlist?

I am not sure, I reinstalled the whole server like a week ago.
May I disable it?

**Comment by JereKuusela** [comment]
If you have only Steam players then you can disable crossplay. Or add your prefab id to the admin list.

**Comment by kkuez** [comment]
> If you have only Steam players then you can disable crossplay. Or add your prefab id to the admin list.

Removing -crossplay is not an option unfortunately.
What do you mean by prefab id?
Adminlist is packed with the players steam64 as needed.
