### ISSUE TITLE
How does one build this?

### ISSUE THREAD

**Issue by AndrewSav** [JereKuusela/valheim-dev#32]
What are assembly_guiutils_publicized, assembly_utils_publicized, assembly_valheim_publicized?

Which versions of BepInEx / Harmony to build against?

Do Unity dependencies come from the game client or game server?

Any building instructions at all?

Many thanks!

**Comment by JereKuusela** [comment]
https://valheim-modding.github.io/Jotunn/guides/guide.html#manual-setup explains how to get publicized assemblies.

https://valheim-modding.github.io/Jotunn/guides/guide.html#bepinex-and-unstripped-unity-dlls how to get Unity and Harmony dlls.

**Comment by AndrewSav** [comment]
@JereKuusela thanks, the links do not work as they are supposed to, but easy enough to find the right pages on the site.
