### ISSUE TITLE
Error entering devcommands in console. 

### ISSUE THREAD

**Issue by simdo01** [JereKuusela/valheim-dev#36]
Running Hildirs Quest update. Receive error when executing "decommands" command. 

`[Error  : Unity Log] MissingFieldException: Field 'Terminal.m_input' not found.
Stack trace:
(wrapper dynamic-method) Terminal.DMD<Terminal::InputText>(Terminal)
Terminal.SendInput () (at <447b19510f604ca3807cd6cce3a7c1ef>:0)
Console.SendInput () (at <447b19510f604ca3807cd6cce3a7c1ef>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <80fe1a4e36fe44618284312cb721a597>:0)
Fishlabs.GuiInputField.onInputSubmit (System.String text) (at <abc2973239274336a7c65e00c9f4ab0e>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <80fe1a4e36fe44618284312cb721a597>:0)
TMPro.TMP_InputField.SendOnSubmit () (at <c3806d8b402548cebcdac84224b2a2a9>:0)
TMPro.TMP_InputField.OnSubmit (UnityEngine.EventSystems.BaseEventData eventData) (at <c3806d8b402548cebcdac84224b2a2a9>:0)
Fishlabs.GuiInputField.OnSubmit (UnityEngine.EventSystems.BaseEventData eventData) (at <abc2973239274336a7c65e00c9f4ab0e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.ISubmitHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.EventSystem:Update()`

**Comment by JereKuusela** [comment]
Remove all mods not made by me.

**Comment by VeggieMeat** [comment]
Just noting that for me, the culprit (found via disabling all then re-enabling one at a time) was aedenthorn_CustomGraphicsSettings v0.7.0.
