### ISSUE TITLE
1.57.0 breaks World Modifier Portal settings

### ISSUE THREAD

**Issue by cjackcandy** [JereKuusela/valheim-dev#37]
To reproduce, change world modifier portals setting to "Portal items" (lowest setting). Start game and note that you cannot teleport with metals/ore. Log out of game and note that the Portals setting has been reset to "Normal". 

Downgrade to 1.56.0 and note that Portals setting will stick.

No other mods were loaded, except latest BeppinEx (v5.4.2105). I'm playing solo on local pc (no server involved).

Also note that the global World Modifier presets "Easy", "Casual" don't stick either with 1.57.0.

**Comment by JereKuusela** [comment]
Thanks, should be now ok with the latest.

**Comment by cjackcandy** [comment]
Fixed! Thank you! :)
