### ISSUE TITLE
Coordinates are being displayed incorrectly!

### ISSUE THREAD

**Issue by Trapaceiro** [JereKuusela/valheim-dev#38]
Why are the coordinates displayed as "X, Z, Y" and not "X, Y, Z"?

As it is, it can cause some confusion because, by a general consensus, "X" is measured along the East-West axis, "Y" is measured along the North-South axis, and "Z" measures height or elevation.

Here is an example:
![image](https://github.com/JereKuusela/valheim-dev/assets/17458432/f4fa1a70-1360-47ae-ac84-5f5fe2ae310f)

Notice that in the original game code, the coordinates are displayed correctly:
![image](https://github.com/JereKuusela/valheim-dev/assets/17458432/9d2bf6e7-3ea4-42e8-adff-9ace0bbc08e7)

**Comment by JereKuusela** [comment]
Elevation is the least important so that's why it is last.

**Comment by Trapaceiro** [comment]
@JereKuusela I agree, this way it gets even better!
But it was my mistake, because the game itself treats "Y" as elevation.
