### ISSUE TITLE
console window with filler text on start

### ISSUE THREAD

**Issue by DredNau9ht-Official** [JereKuusela/valheim-dev#40]
Since I updated this morning the game has become unplayable have narrowed it down to this mod when game launches I get this...
![image](https://github.com/JereKuusela/valheim-dev/assets/113311420/0e1f4c62-2015-4126-a59b-c682e41ac9aa)

And when I enter the game my character spins and no inputs work

**Comment by Tuumke** [comment]
+1, same issue. denikson-BepInExPack_Valheim had an update, might have to do with that

**Comment by JereKuusela** [comment]
Some text is vanilla thing.
