### ISSUE TITLE
Server_Dev commands

### ISSUE THREAD

**Issue by Shalindra-storm** [JereKuusela/valheim-dev#47]
With the first update on 1/17 24  ver. 1.71.0 the command "spawn" was broken. You can type it in, there are no errors reported in the command window, but nothing gets spawned. I have tested this by turning off the mod and through normal "devcommand"   I can spawn items, I also checked my no modded server and hadno problems..  This is affecting all the servers running the Server_Dev mod.

**Comment by Trapaceiro** [comment]
For me it still works normally!
