### ISSUE TITLE
Error when trying to use devcommands in game dedicated server

### ISSUE THREAD

**Issue by Morpheus1101** [JereKuusela/valheim-dev#54]
[ModVersion: 1.77.0] When i type devcommand into the terminal on multiplayer dedi server, the below is what instantly occurs..

[Error  : Unity Log] TypeLoadException: Failure has occurred while loading a type.
Stack trace:
(wrapper dynamic-method) Terminal.DMD<Terminal::InputText>(Terminal)
Terminal.SendInput () (at <da52c09f594f4a7480000b7420815ba7>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
GUIFramework.GuiInputField.onInputSubmit (System.String text) (at <1c0bbb94c86e42bb92d9376327e3b555>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
TMPro.TMP_InputField.SendOnSubmit () (at <99900a1f9e2a471c8b46c2c560e4eba9>:0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <99900a1f9e2a471c8b46c2c560e4eba9>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <a01fe238487248d39ba352ec152ec890>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <a01fe238487248d39ba352ec152ec890>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by JereKuusela** [comment]
Uninstall InstantMonsterLootDrop.

Unlikely that it gets updated.
