### ISSUE TITLE
Unable to use devcommands or debugmode

### ISSUE THREAD

**Issue by KnightBugg** [JereKuusela/valheim-dev#55]
Since the new update of server_devcommands to 1.77.0 and Valheim recent update I am unable to use commands. 
![1](https://github.com/JereKuusela/valheim-dev/assets/167139831/d4726736-293a-4d2e-89f9-7fb67891ef31)
![2](https://github.com/JereKuusela/valheim-dev/assets/167139831/7a0ca0b6-dbc3-41de-95f7-357df5a137ba)

**Comment by Jester2020** [comment]
I'm experiencing the same issues with all the commands i've tried so far.

**Comment by Jester2020** [comment]
I'm getting the same error but i disabled Server Devcommands and i'm still getting it so we're likely using some of the same mods or mod that is causing the issue.

**Comment by KnightBugg** [comment]
I am using all of Therzie mods as the big overhaul
![3](https://github.com/JereKuusela/valheim-dev/assets/167139831/97973c87-f704-4433-899f-cc2496d58620)
![4](https://github.com/JereKuusela/valheim-dev/assets/167139831/72b4fd5a-e307-4706-a4c7-19e89eaac8d4)

**Comment by SauceyGit** [comment]
From the patch notes for v.0.217.26

> Upgraded Unity engine to 2022.3.17f

These error messages speak to a unity engine issue. Not only does the plugin need to be updated to be in sync with the release, the version of Unity in use by the client, itself, is incompatible.

**Comment by SauceyGit** [comment]
> there is no v.0.217.26 i am assuming you meant .46

Indeed. Fixed.

**Comment by Jester2020** [comment]
For those of you experiencing this issue. Craft From Containers and Show Container Contents both were causing the issue for me. It definitely was not Server DevCommands. So if you are using either of those try disabling them and using the F5 Console.

**Comment by Opus1369** [comment]
> For those of you experiencing this issue. Craft From Containers and Show Container Contents both were causing the issue for me. It definitely was not Server DevCommands. So if you are using either of those try disabling them and using the F5 Console.

we dont use those...... and yet the issue persists

**Comment by SauceyGit** [comment]
They may be having the same issue that DevCommands is, but that doesn't mean they're causing the issue in DevCommands. The plugin hasn't been updated since Iron Gate upgraded the version of the Unity Engine that Valheim uses.

**Comment by JereKuusela** [comment]
If you still have issues, uninstall mods not made by me. Preferably starting with the older ones.

I will close this for now because this place is not really meant to discuss issues of other mods.

**Comment by SauceyGit** [comment]
Truth @JereKuusela .

I went back to QA steps and disabled all but DevCommands.

DevCommands worked just fine.

So far, Auto_Feed by LordJay throws errors when trying to use the dev command console, when enabled. It's just odd that plugin would do that, but not throw errors when _in use_ (i.e. chuck carrots in a bin and the boars eat them without issue).

**Comment by MasonBlack42** [comment]
This problem persists for me. It did not happen until I installed this mod. I followed the installation instructions and god mode does not work. I removed the mod. This error happened.
