### ISSUE TITLE
Can't build (compilation failure)

### ISSUE THREAD

**Issue by SuEuMesma** [JereKuusela/valheim-dev#58]
Get error in:
`valheim-dev\ServerDevcommands\Features\AutomaticPickUp.cs(6,5)`

I'm using dependencies from the latest version of Valheim.

**Comment by SuEuMesma** [comment]
I solved the problem by removing the AutomaticPickUp.cs file and everything related to it. Because I couldn't test if the feature still works.

**Comment by JereKuusela** [comment]
This is now fixed, thanks!
