### ISSUE TITLE
Access private chests is causing some problems if there is someone nearby

### ISSUE THREAD

**Issue by SuEuMesma** [JereKuusela/valheim-dev#61]
How to reproduce:
If you arrive at the instance and there is already a player there, it will appear that someone is already using that chest, even if the player has not even touched the chest. And if the player there is the creator of the private chest, there will be instability in your connection (tested in crossplay only).

However, if you are alone or are the first to arrive at the instance, the feature works normally.

**Comment by JereKuusela** [comment]
You can't force another client to let you open the chest. Only when your client controls the chest you can do that.

I can change it later to forcefully open the chest but that of course means items might get duped if two clients use the chest at the same time.

Instability sounds weird though.

**Comment by SuEuMesma** [comment]
> You can't force another client to let you open the chest. Only when your client controls the chest you can do that.
> 
> I can change it later to forcefully open the chest but that of course means items might get duped if two clients use the chest at the same time.
> 
> Instability sounds weird though.

After this update, it no longer causes connection problems if the owner of the chest is nearby before you. However, you still can't open the chest. It looks like it's resolved. Thank you.
