### ISSUE TITLE
find command does not work on hosted server

### ISSUE THREAD

**Issue by rossum** [JereKuusela/valheim-dev#71]
This is in version 0.218.12.

When running a local hosted world, in debugmode, type e.g. "find MountainCave02" or "find MountainCave02 2000" and you will get a list of results plus map pings.

When running on a hosted world, the same command does not provide results.

Thanks for looking into this!

**Comment by JereKuusela** [comment]
From readme:

Some features and commands require also installing the mod on the server (event, **find**, randomevent, stopevent).

Is the mod installed on the server too?

**Comment by rossum** [comment]
Whoops! That was it. Mod working as expected.

Thank you!
